In [23]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

In [24]:
data = keras.datasets.mnist
(train_images, train_labels), (test_images, test_labels) = data.load_data()

In [25]:
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [26]:
train_labels[0]

5

In [27]:
train_images = train_images / 255.0
test_images = test_images / 255.0


In [28]:
train_images[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [29]:
total_classes = 10
train_vec_labels = keras.utils.to_categorical(train_labels, total_classes)
test_vec_labels = keras.utils.to_categorical(test_labels, total_classes)

In [30]:
train_vec_labels[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [31]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation='sigmoid'), 
    keras.layers.Dense(10, activation='sigmoid')
])

In [32]:
model.compile(
    optimizer='sgd',
    loss='mean_squared_error',
    metrics=['accuracy'])

In [33]:
model.fit(train_images,train_vec_labels,epochs=7,verbose=True)

Epoch 1/7
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1091 - accuracy: 0.1740
Epoch 2/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0883 - accuracy: 0.3218
Epoch 3/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0871 - accuracy: 0.3991
Epoch 4/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0859 - accuracy: 0.4343
Epoch 5/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0845 - accuracy: 0.4615
Epoch 6/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0830 - accuracy: 0.4878
Epoch 7/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0813 - accuracy: 0.5116


In [34]:
model.compile(
    optimizer='adam',
    loss='mean_squared_error',
    metrics=['accuracy'])

In [35]:
model.fit(train_images,train_vec_labels,epochs=7,verbose=True)

Epoch 1/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0200 - accuracy: 0.8971
Epoch 2/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0108 - accuracy: 0.9384
Epoch 3/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0083 - accuracy: 0.9528
Epoch 4/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0068 - accuracy: 0.9619
Epoch 5/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0058 - accuracy: 0.9685
Epoch 6/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0050 - accuracy: 0.9735
Epoch 7/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0044 - accuracy: 0.9774


In [36]:
model.compile(
    optimizer='sgd',
    loss='categorical_crossentropy',
    metrics=['accuracy'])

In [37]:
model.fit(train_images,train_vec_labels,epochs=7,verbose=True)

Epoch 1/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0772 - accuracy: 0.9809
Epoch 2/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0750 - accuracy: 0.9812
Epoch 3/7
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0735 - accuracy: 0.9815
Epoch 4/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0721 - accuracy: 0.9816
Epoch 5/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0711 - accuracy: 0.9822
Epoch 6/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0701 - accuracy: 0.9825
Epoch 7/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0692 - accuracy: 0.9826


In [38]:
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy'])

In [39]:
model.fit(train_images,train_vec_labels,epochs=7,verbose=True)

Epoch 1/7
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0709 - accuracy: 0.9817
Epoch 2/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0568 - accuracy: 0.9848
Epoch 3/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0474 - accuracy: 0.9869
Epoch 4/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0395 - accuracy: 0.9896
Epoch 5/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0333 - accuracy: 0.9912
Epoch 6/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0279 - accuracy: 0.9931
Epoch 7/7
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0230 - accuracy: 0.9949


In [40]:
eval_loss, eval_accuracy = model.evaluate(test_images, test_vec_labels, verbose=False)
print("Model accuracy: %.2f" % eval_accuracy)

Model accuracy: 0.98
